repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: detect-private-key
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: name-tests-test
    - id: requirements-txt-fixer
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.10.0
  hooks:
  - id: black
    language_version: python3.12
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
