version: "3.8"

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_ticket_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:
