version: "3.8"

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_ticket_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

#  ticket_system:
#    build:
#      dockerfile: Dockerfile
#    container_name: ticket_system
#    command: gunicorn --config app/gunicorn.conf.py app.main:app
#    ports:
#      - "8000:8000"
#    volumes:
#      - .:/ticket_system
#    depends_on:
#      - postgres_db

volumes:
  postgres_data:
